//AWS Exports
import * as ElasticBeanstalk from './ElasticBeanstalk';
export {ElasticBeanstalk};
import * as AmazonMQ from './AmazonMQ';
export {AmazonMQ};
import * as EC2 from './EC2';
export {EC2};
import * as AppSync from './AppSync';
export {AppSync};
import * as ServiceCatalog from './ServiceCatalog';
export {ServiceCatalog};
import * as Cognito from './Cognito';
export {Cognito};
import * as Events from './Events';
export {Events};
import * as WAF from './WAF';
export {WAF};
import * as IAM from './IAM';
export {IAM};
import * as CodePipeline from './CodePipeline';
export {CodePipeline};
import * as Elasticsearch from './Elasticsearch';
export {Elasticsearch};
import * as ApiGateway from './ApiGateway';
export {ApiGateway};
import * as WAFRegional from './WAFRegional';
export {WAFRegional};
import * as RDS from './RDS';
export {RDS};
import * as EMR from './EMR';
export {EMR};
import * as WorkSpaces from './WorkSpaces';
export {WorkSpaces};
import * as Logs from './Logs';
export {Logs};
import * as Kinesis from './Kinesis';
export {Kinesis};
import * as AutoScaling from './AutoScaling';
export {AutoScaling};
import * as SQS from './SQS';
export {SQS};
import * as AutoScalingPlans from './AutoScalingPlans';
export {AutoScalingPlans};
import * as AppStream from './AppStream';
export {AppStream};
import * as Route53 from './Route53';
export {Route53};
import * as CloudWatch from './CloudWatch';
export {CloudWatch};
import * as ECS from './ECS';
export {ECS};
import * as ElasticLoadBalancingV2 from './ElasticLoadBalancingV2';
export {ElasticLoadBalancingV2};
import * as Neptune from './Neptune';
export {Neptune};
import * as StepFunctions from './StepFunctions';
export {StepFunctions};
import * as KinesisAnalytics from './KinesisAnalytics';
export {KinesisAnalytics};
import * as OpsWorks from './OpsWorks';
export {OpsWorks};
import * as CloudFront from './CloudFront';
export {CloudFront};
import * as GameLift from './GameLift';
export {GameLift};
import * as GuardDuty from './GuardDuty';
export {GuardDuty};
import * as DirectoryService from './DirectoryService';
export {DirectoryService};
import * as SNS from './SNS';
export {SNS};
import * as EFS from './EFS';
export {EFS};
import * as SSM from './SSM';
export {SSM};
import * as SageMaker from './SageMaker';
export {SageMaker};
import * as Config from './Config';
export {Config};
import * as KMS from './KMS';
export {KMS};
import * as Redshift from './Redshift';
export {Redshift};
import * as Lambda from './Lambda';
export {Lambda};
import * as CertificateManager from './CertificateManager';
export {CertificateManager};
import * as IoT1Click from './IoT1Click';
export {IoT1Click};
import * as Inspector from './Inspector';
export {Inspector};
import * as IoTAnalytics from './IoTAnalytics';
export {IoTAnalytics};
import * as Batch from './Batch';
export {Batch};
import * as ASK from './ASK';
export {ASK};
import * as OpsWorksCM from './OpsWorksCM';
export {OpsWorksCM};
import * as IoT from './IoT';
export {IoT};
import * as ElasticLoadBalancing from './ElasticLoadBalancing';
export {ElasticLoadBalancing};
import * as DMS from './DMS';
export {DMS};
import * as Glue from './Glue';
export {Glue};
import * as ElastiCache from './ElastiCache';
export {ElastiCache};
import * as CodeDeploy from './CodeDeploy';
export {CodeDeploy};
import * as SES from './SES';
export {SES};
import * as SecretsManager from './SecretsManager';
export {SecretsManager};
import * as CodeBuild from './CodeBuild';
export {CodeBuild};
import * as Budgets from './Budgets';
export {Budgets};
import * as DAX from './DAX';
export {DAX};
import * as DataPipeline from './DataPipeline';
export {DataPipeline};
import * as Route53Resolver from './Route53Resolver';
export {Route53Resolver};
import * as CloudTrail from './CloudTrail';
export {CloudTrail};
import * as CloudFormation from './CloudFormation';
export {CloudFormation};
import * as Cloud9 from './Cloud9';
export {Cloud9};
import * as ServiceDiscovery from './ServiceDiscovery';
export {ServiceDiscovery};
import * as EKS from './EKS';
export {EKS};
import * as ApplicationAutoScaling from './ApplicationAutoScaling';
export {ApplicationAutoScaling};
import * as CodeCommit from './CodeCommit';
export {CodeCommit};
import * as S3 from './S3';
export {S3};
import * as KinesisFirehose from './KinesisFirehose';
export {KinesisFirehose};
import * as DLM from './DLM';
export {DLM};
import * as SDB from './SDB';
export {SDB};
import * as ECR from './ECR';
export {ECR};
import * as DynamoDB from './DynamoDB';
export {DynamoDB};
import * as Athena from './Athena';
export {Athena};
